### ISSUE TITLE
After successful payment, redirecting to localhost

### ISSUE THREAD

**Issue by kuntalk** [NyanKiyoshi/django-payments-razorpay#2]
I have deployed it in heroku. So, after successful payment, it is getting redirected to http://localhost:8000/en/order/67251c0e-ad9d-4f62-a9fd-560c6f571b1f/checkout-success/

You can check by placing order, now only test payment is there. So no money will get deducted.
Here is the [url ](http://thenutririch.herokuapp.com/en/) to that store @NyanKiyoshi

**Comment by NyanKiyoshi** [comment]
Hi!

Did you set the domain in your Saleor dashboard? (dashboard > site settings). That should be the issue.

**Comment by kuntalk** [comment]
Yes, now it is working fine. Thanks.
