### ISSUE TITLE
Detailed instructions on how to use this thing?

### ISSUE THREAD

**Issue by nishat-sayyed** [NyanKiyoshi/django-payments-razorpay#4]

**Comment by NyanKiyoshi** [comment]
Hi! 

Refer to the documentation of django-payments: https://django-payments.readthedocs.io/en/latest/install.html for more details on how to use the django-payments.

On top, django-payments-razorpay has the information on how to configure django-payments: https://github.com/NyanKiyoshi/django-payments-razorpay/blob/4cf0b6a/README.md

In your django `settings.py`, the only additional thing you need is to update your `PAYMENT_VARIANTS` entry to add the `razorpay` provider.

```
PAYMENT_VARIANTS = {
    'razorpay': ('django_payments_razorpay.RazorPayProvider', {
        'public_key': 'RAZORPAY_PUBLIC_KEY',
        'secret_key': 'RAZORPAY_SECRET_KEY'})}
```

Feel free to contact if any additional questions.

**Comment by djb4ai** [comment]
@NyanKiyoshi I think it should be mentioned in the readme as well that this is a plugin for `django-payments`
